[09:24] Santhosh Kumar Kadaveru
    
TARGET = all.out
$(TARGET): main.c myutils.c mystring.c bitmask.c
    gcc main.c myutils.c mystring.c bitmask.c -o all.out
main.o: main.c mystring.h myutils.h bitmask.h
    gcc -c main.c


myutils.o: myutils.c myutils.h 
    gcc -c myutils.c


mystring.o: mystring.c mystring.h
    gcc -c mystring.c


bitmask.o: bitmask.c bitmask.h
    gcc -c bitmask.c
clean:
    rm *.o *.out





